# Generated by Django 4.2.5 on 2024-02-07 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_projectfile_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("body", models.TextField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
